version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - mysql
      - flyway
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Qwerty_123
      MYSQL_DATABASE: sys
    ports:
      - "3307:3306"
    volumes:
      - ./sys:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://mysql:3306/sys -user=root -password=Qwerty_123 migrate -locations=filesystem:migrat
    volumes:
      - ./migrat:/flyway/sql
    depends_on:
      - mysql
    networks:
      - mynetwork
    network_mode: bridge

networks:
  mynetwork:
