version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Qwerty_123
      MYSQL_DATABASE: sys
    ports:
      - "3307:3306"
    volumes:
      - ./sys:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - mynetwork

networks:
  mynetwork:

